### ISSUE TITLE
Add more checks on commandLine of a requester

### ISSUE THREAD

**Issue by jeremyjams** [iExecBlockchainComputing/iexec-core#216]
A call by a requester of a deal has been made with `{ "1BTC"}` instead of doing `{ "0": "1BTC"}`
```
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
 at [Source: ["1BTC"]; line: 1, column: 1]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
    at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromEmpty(StdDeserializer.java:892)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:358)
    at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842)
    at com.iexec.common.chain.ChainDeal.stringParamsToList(ChainDeal.java:50)
    at com.iexec.common.chain.ChainUtils.getChainDeal(ChainUtils.java:132)
    at com.iexec.core.chain.IexecHubService.getChainDeal(IexecHubService.java:279)
    at com.iexec.core.chain.DealWatcherService.handleDeal(DealWatcherService.java:62)
    at com.iexec.core.chain.DealWatcherService.onDealEvent(DealWatcherService.java:55)
    at java.util.Optional.ifPresent(Optional.java:159)
    at com.iexec.core.chain.DealWatcherService.lambda$subscribeToDealEventInRange$2(DealWatcherService.java:105)
```

**Comment by jeremyjams** [comment]
Done in https://github.com/iExecBlockchainComputing/iexec-common/pull/98
