### ISSUE TITLE
Task status passes to "contribution timeout" even though it is just created

### ISSUE THREAD

**Issue by zguesmi** [iExecBlockchainComputing/iexec-core#352]
Bought a deal:
```
app:        0x39078bC82CC49bD6eaE52ed484b422f387571A0B (0 nRLC)
workerpool: 0x706bB37Fb0545aD82f02721cDe7B8F9d351390Ec (0 nRLC)
params:     python3 /app/app.py
category:   3
tag:        0x0000000000000000000000000000000000000000000000000000000000000001
 Yes
ℹ deal submitted with dealid 0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398
⡋⠁ ▶ Watching tasks execution...
- Task idx 0 (0x55409919eade969739a1b86f36b2f87a2adde38ef488492d17dedb413aa4ba29) status UNSET
```
Task on the explorer:
https://explorer.iex.ec/goerli/deal/0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398
Final time: Tue Feb 11 2020 17:47:43 GMT+0100

Core logs:
```
2020-02-10 10:47:28.986  INFO 1 --- [pool-2-thread-3] com.iexec.core.chain.DealWatcherService  : Received deal [dealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, block:2153428]
2020-02-10 10:47:29.227  INFO 1 --- [pool-2-thread-3] com.iexec.core.task.TaskService          : Add new task [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, imageName:registry.hub.docker.com/iexechub/vanityeth:1.1.1, commandLine:python3 /app/app.py, trust:1]
2020-02-10 10:47:29.229  INFO 1 --- [pool-2-thread-3] c.i.core.task.listener.TaskListeners     : Received TaskCreatedEvent [chainTaskId:0x55409919eade969739a1b86f36b2f87a2adde38ef488492d17dedb413aa4ba29]
2020-02-10 10:47:29.233  INFO 1 --- [pool-2-thread-3] com.iexec.core.chain.DealWatcherService  : Received deal [dealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, block:2153428]
2020-02-10 10:47:29.645  INFO 1 --- [pool-2-thread-3] com.iexec.core.task.TaskService          : Task already added [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, imageName:registry.hub.docker.com/iexechub/vanityeth:1.1.1, commandLine:python3 /app/app.py, trust:1]
2020-02-10 10:47:29.646  INFO 1 --- [pool-2-thread-3] com.iexec.core.chain.DealWatcherService  : Received deal [dealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, block:2153429]
2020-02-10 10:47:29.738  INFO 1 --- [ol-830-thread-1] com.iexec.core.task.TaskService          : UpdateTaskStatus suceeded [chainTaskId:0x55409919eade969739a1b86f36b2f87a2adde38ef488492d17dedb413aa4ba29, currentStatus:RECEIVED, newStatus:INITIALIZING]
2020-02-10 10:47:29.739  INFO 1 --- [ol-830-thread-1] com.iexec.core.chain.IexecHubService     : Requested  initialize [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, waitingTxCount:0]
2020-02-10 10:47:29.881  INFO 1 --- [pool-2-thread-3] com.iexec.core.task.TaskService          : Task already added [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, imageName:registry.hub.docker.com/iexechub/vanityeth:1.1.1, commandLine:python3 /app/app.py, trust:1]
2020-02-10 10:47:58.987  INFO 1 --- [pool-2-thread-2] com.iexec.core.chain.DealWatcherService  : Received deal [dealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, block:2153429]
2020-02-10 10:47:59.240  INFO 1 --- [pool-2-thread-2] com.iexec.core.task.TaskService          : Task already added [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, imageName:registry.hub.docker.com/iexechub/vanityeth:1.1.1, commandLine:python3 /app/app.py, trust:1]
2020-02-10 10:47:59.241  INFO 1 --- [pool-2-thread-2] com.iexec.core.chain.DealWatcherService  : Received deal [dealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, block:2153430]
2020-02-10 10:47:59.490  INFO 1 --- [pool-2-thread-2] com.iexec.core.task.TaskService          : Task already added [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, imageName:registry.hub.docker.com/iexechub/vanityeth:1.1.1, commandLine:python3 /app/app.py, trust:1]
2020-02-10 10:47:59.492  INFO 1 --- [pool-2-thread-2] com.iexec.core.chain.DealWatcherService  : Received deal [dealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, block:2153430]
2020-02-10 10:47:59.730  INFO 1 --- [pool-2-thread-2] com.iexec.core.task.TaskService          : Task already added [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, imageName:registry.hub.docker.com/iexechub/vanityeth:1.1.1, commandLine:python3 /app/app.py, trust:1]
2020-02-10 10:47:59.731  INFO 1 --- [pool-2-thread-2] com.iexec.core.chain.DealWatcherService  : Received deal [dealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, block:2153430]
2020-02-10 10:47:59.980  INFO 1 --- [pool-2-thread-2] com.iexec.core.task.TaskService          : Task already added [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, imageName:registry.hub.docker.com/iexechub/vanityeth:1.1.1, commandLine:python3 /app/app.py, trust:1]
2020-02-10 10:47:59.981  INFO 1 --- [pool-2-thread-2] com.iexec.core.chain.DealWatcherService  : Received deal [dealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, block:2153430]
2020-02-10 10:48:00.047 ERROR 1 --- [pool-4-thread-1] com.iexec.core.chain.IexecHubService     : Failed to send initialize [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, exception:Transaction has failed with status: 0x0. Gas used: 52846. (not-enough gas?)]
org.web3j.protocol.exceptions.TransactionException: Transaction has failed with status: 0x0. Gas used: 52846. (not-enough gas?)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:372)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:345)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:339)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:334)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:399)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:42)
	at com.iexec.core.chain.IexecHubService.sendInitializeTransaction(IexecHubService.java:130)
	at com.iexec.core.chain.IexecHubService.lambda$initialize$1(IexecHubService.java:111)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2020-02-10 10:48:00.102  INFO 1 --- [ol-830-thread-1] com.iexec.core.task.TaskService          : UpdateTaskStatus suceeded [chainTaskId:0x55409919eade969739a1b86f36b2f87a2adde38ef488492d17dedb413aa4ba29, currentStatus:INITIALIZING, newStatus:INITIALIZED]
2020-02-10 10:48:00.219  INFO 1 --- [pool-2-thread-2] com.iexec.core.task.TaskService          : Task already added [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, imageName:registry.hub.docker.com/iexechub/vanityeth:1.1.1, commandLine:python3 /app/app.py, trust:1]
2020-02-10 10:48:00.220  INFO 1 --- [pool-2-thread-2] com.iexec.core.chain.DealWatcherService  : Received deal [dealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, block:2153430]
2020-02-10 10:48:00.520  INFO 1 --- [pool-2-thread-2] com.iexec.core.task.TaskService          : Task already added [chainDealId:0x77cf113e6ba022caa8a4dc4a751e2e076c3fcb236470793ac3208cd201a07398, taskIndex:0, imageName:registry.hub.docker.com/iexechub/vanityeth:1.1.1, commandLine:python3 /app/app.py, trust:1]
2020-02-10 10:48:24.846  INFO 1 --- [MessageBroker-7] .i.c.d.t.ContributionTimeoutTaskDetector : Task with contribution timeout found [chainTaskId:0x55409919eade969739a1b86f36b2f87a2adde38ef488492d17dedb413aa4ba29]
2020-02-10 10:48:24.847  INFO 1 --- [ol-830-thread-1] com.iexec.core.task.TaskService          : UpdateTaskStatus suceeded [chainTaskId:0x55409919eade969739a1b86f36b2f87a2adde38ef488492d17dedb413aa4ba29, currentStatus:INITIALIZED, newStatus:CONTRIBUTION_TIMEOUT]
2020-02-10 10:48:24.848  INFO 1 --- [ol-830-thread-1] com.iexec.core.task.TaskService          : UpdateTaskStatus suceeded [chainTaskId:0x55409919eade969739a1b86f36b2f87a2adde38ef488492d17dedb413aa4ba29, currentStatus:CONTRIBUTION_TIMEOUT, newStatus:FAILED]
2020-02-10 10:48:24.849  INFO 1 --- [ol-830-thread-1] c.i.core.task.listener.TaskListeners     : Received ContributionTimeoutEvent [chainTaskId:0x55409919eade969739a1b86f36b2f87a2adde38ef488492d17dedb413aa4ba29] 
2020-02-10 10:48:24.849  INFO 1 --- [ol-830-thread-1] c.iexec.core.pubsub.NotificationService  : Sent TaskNotification [chainTaskId:0x55409919eade969739a1b86f36b2f87a2adde38ef488492d17dedb413aa4ba29, type:PLEASE_ABORT_CONTRIBUTION_TIMEOUT, workers:[]]
2020-02-10 10:48:24.850  INFO 1 --- [ol-830-thread-1] c.i.core.task.listener.TaskListeners     : NotifyAbortContributionTimeout completed[workerAddresses:[]]
```

**Comment by jeremyjams** [comment]
Fixed in https://github.com/iExecBlockchainComputing/iexec-common/pull/222.

A deal is made of multiple parts: part1, part2 and config (not mentioning external references to app, dataset & category). If a chain reorg happens while on-chain reading a deal, all attributes of a part could be set to empty (0x0), leading to a partially wrong deal object.
Checking non-emptiness of some attributes would reduce errors on client side. It is better for them to read nothing instead of something partially wrong.

In this PR, we ensure startTime and maxExecutionTime are properly set.
